### ISSUE TITLE
Implement E2E test for Basic Filter step

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-e2e-tests#13]
Based on this [Filtering epic issue](https://github.com/syndesisio/syndesis-project/issues/2) create E2E test that will verify addition of filter to integrations. 

Should be doable after PR https://github.com/syndesisio/syndesis-ui/pull/582 is merged.

**Comment by dsimansk** [comment]
I've changed the scope of this task to cover only Basic Filter. There are 2 types of filters now. Basic Filter which was delivered from Spring 14. And Advance Filter that allows to use usual Camel filter expressions, this is planned to be enhanced further with code editor, documentation link and example usage. 

Please prepare only test for Basic Filter as the UI is rather complex, with input boxes etc.

**Comment by lvydra** [comment]
"Add another rule" link is not working on Basic Filter page. Should it be functional?

**Comment by dsimansk** [comment]
I've found the issue reported, but still not resolved https://github.com/syndesisio/syndesis-ui/issues/631. So it should be functional, but it isn't right now :)

**Comment by lvydra** [comment]
After leaving  basic filter step definition and returning back, all fields are reset to initial (blank) state. Is it intentional?

**Comment by dsimansk** [comment]
Done via #62.
