### ISSUE TITLE
Twitter Listener is renamed to Twitter Example

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-e2e-tests#36]
Not valid anymore.

```gherkin
When Camilla selects the "Twitter Listener" connection
```

@jludvice how cool it would be to load the names upon suite start? :)

**Comment by jludvice** [comment]
@dsimansk I don't think we want to do that -> one more thing to go wrong imho :(
Why is it not valid anymore?

This connection should be created as part of `@datamapper` e2e test.
https://github.com/syndesisio/syndesis-e2e-tests/pull/1/files#diff-9a8ae2f50cc0264d26b8d6df57963b0eR18

What changed?

**Comment by dsimansk** [comment]
${title} says it all :)

**Comment by jludvice** [comment]
Who and why renamed my connection ?

**Comment by dsimansk** [comment]
Nevermind, the create connection page is not loading my bad.

**Comment by dsimansk** [comment]
I've opened issue to track this https://github.com/syndesisio/syndesis-ui/issues/645. Once again I'm sorry that I missed the root cause and deducted wrong conclusion :)

**Comment by dsimansk** [comment]
Root cause is fixed, closing.
