### ISSUE TITLE
Load github user credentials from json settings

### ISSUE THREAD

**Issue by jludvice** [syndesisio/syndesis-e2e-tests#37]
We introduced json with settings/credentials for e2e test in #1.
Load github credentials from that json instead of shell environments.

Do you agree @dsimansk @lvydra ?

**Comment by lvydra** [comment]
I like that.

**Comment by jludvice** [comment]
@dsimansk @lvydra working progress PR #45 
I'm not very happy with this referencing of user, open for suggestions ;)
https://github.com/jludvice/syndesis-e2e-tests/blob/github-credentials/e2e/common/common.steps.ts#L31

**Comment by dsimansk** [comment]
I would prefer something like TestConfiguration object initialised ath the start that is accessible from all around. That should hold all the necessary configs and wrap the loading of it. Wdyt?

**Comment by jludvice** [comment]
@dsimansk such object is present since my last PR. See `world.testConfig`:
https://github.com/syndesisio/syndesis-e2e-tests/blob/master/e2e/common/world.ts#L59

Technically  `users: Map<string, User>;` has exactly the same data as `world.testConfig.users` (it's actually a sourse of data for users property).
I introduced `users` map to have it "typed".

**Comment by jludvice** [comment]
Can we leave UI url defined as shell env `SYNDESIS_UI_URL` ?
It's needed in `protractor.conf.js`.
It's evaluated much sooner than we parse `test-config.json` and we'd have to do it twice. One for protractor and second for e2e `world` object.

**Comment by dsimansk** [comment]
Sure, lets keep it then.

**Comment by jludvice** [comment]
Resolved by #45
