### ISSUE TITLE
Create scenario to capture screenshots of UI in various res.

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-e2e-tests#42]
Create annotation like `@screenshots` that will have very narrow gherkin scenario. It'll visit all pages and capture screenshot in the process.

Also investigate the possibility how to set up different resolutions (through protractor conf), currently we specify it in [run script](https://github.com/syndesisio/syndesis-e2e-tests/blob/master/e2e-xvfb.sh#L3)

Lets start with the current res, Full HD and something smaller 800x640 maybe.

@jimmidyson feel free to chime in and specify any other details :)

**Comment by jludvice** [comment]
@dsimansk this should be pretty easy
```ts
  @when(/^Change browser resolution to "([^"]*)" x "([^"]*)"$/)
  public changeResolution (width, height): P<any> {
    const x = Number(width);
    const y = Number(height);
    log.warn(`Changing browser resolution to ${x}x${y}`);
    return browser.manage().window().setSize(x, y);
  }
```

```gherkin
@screenshot
Feature: Take screenshots in various resolutions
  https://github.com/syndesisio/syndesis-e2e-tests/issues/42

  Scenario: asdfasdf
    When "Camilla" logs into the Syndesis URL for her installation (e.g. rh-syndesis.[openshift online domain].com)
    And Change browser resolution to "800" x "600"
```

**Comment by dsimansk** [comment]
@mmelko see Josef's last comment with hint to change res.

**Comment by jludvice** [comment]
and here is fix for proper function of scrolling #52

```gherkin
  Scenario: asdfasdf
    When "Camilla" logs into the Syndesis URL for her installation (e.g. rh-syndesis.[openshift online domain].com)
    And Change browser resolution to "800" x "600"
    And scroll "bottom" "left"
```

**Comment by dsimansk** [comment]
Done via #63.

**Comment by dsimansk** [comment]
@jimmidyson example of screenshot can be found in [our CI](https://jenkins-syndesis-ci.b6ff.rh-idev.openshiftapps.com/job/syndesis-e2e-tests/job/master/lastSuccessfulBuild/artifact/e2e/cucumber-reports/screenshots/screenshots.html).

**Comment by jimmidyson** [comment]
Brilliant work! Well done team!
